---
server:
  port: 8080
    #spring:
    #datasource:
    #url: jdbc:mariadb://localhost:3306/cbBlog
    #username:
    #password:
    #driver-class-name: org.mariadb.jdbc.Driver
    #jpa:
    # Use the below line for Test/Dev Environments.
  # hibernate.ddl-auto: create-drop
  # Use the below line for Prod Environment.
  # hibernate.ddl-auto: none
  logging:
    level:
      root: DEBUG
      org.springframework: DEBUG
      dev.christopherbell.azurras: DEBUG
image-properties:
  images:
    - name: The River Walk - San Antonio
      path: /images/photos/IMG_0072.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: The Gardens - Denver
      path: /images/photos/IMG_0130.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: The Strip - Las Vegas
      path: /images/photos/IMG_0257.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: The Lake - New Orleans"
      path: /images/photos/IMG_0390.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: The Austin Skyline - Austin
      path: /images/photos/IMG_0691.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: Parakeet Eats - New Orleans
      path: /images/photos/IMG_0947.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: The Beach - Miami Beach
      path: /images/photos/IMG_1614.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: The Colorado River - Austin
      path: /images/photos/IMG_1666.JPG
      desc: n/a
      date-added: 8-31-2021
    - name: The Austin Skyline 2 - Austin
      path: /images/photos/IMG_1668.JPG
      desc: n/a
      date-added: 8-31-2021
    - name: NA Miata - Austin
      path: /images/photos/IMG_1350.jpeg
      desc: n/a
      date-added: 8-31-2021