server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework: INFO
    dev.christopherbell.blog: DEBUG
---
spring:
  profiles:
    default: local
  datasource:
    url: jdbc:postgresql://localhost:5432/christopherbell.dev
    username: postgres
    password: postgres
    #    jpa:
    #        hibernate:
    #            ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: void-api
        dialect: org.hibernate.dialect.PostgreSQLDialect
blog-properties:
  posts:
    - author: Test
      contentText: Test Content
      date: 10-1-2022
      description: test description
      id: "021e2435-7259-4b48-99a0-e4ce43f3948f"
      imagePath: N/A
      tags:
        - testTag
        - testTag2
      title: test blog
photo-properties:
  images:
    - name: The River Walk - San Antonio
      path: /images/photos/IMG_0072.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: The Gardens - Denver
      path: /images/photos/IMG_0130.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: The Strip - Las Vegas
      path: /images/photos/IMG_0257.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: The Lake - New Orleans"
      path: /images/photos/IMG_0390.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: The Austin Skyline - Austin
      path: /images/photos/IMG_0691.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: Parakeet Eats - New Orleans
      path: /images/photos/IMG_0947.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: The Beach - Miami Beach
      path: /images/photos/IMG_1614.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: The Colorado River - Austin
      path: /images/photos/IMG_1666.JPG
      desc: n/a
      date-added: 8-31-2021
    - name: The Austin Skyline 2 - Austin
      path: /images/photos/IMG_1668.JPG
      desc: n/a
      date-added: 8-31-2021
    - name: NA Miata - Austin
      path: /images/photos/IMG_1350.jpeg
      desc: n/a
      date-added: 8-31-2021
    - name: Denver Botanic Gardens - Outside Tropical Plants Enclosure
      path: /images/photos/IMG_1854.jpeg
      desc: The outside view of the building that contains the Tropical Plants from the Denver Botanic Gardens.
      date-added: 10-24-2021
    - name: Denver Botanic Gardens
      path: /images/photos/IMG_1836.jpeg
      desc: n/a
      date-added: 10-24-2021
wfl-properties:
  restaurants:
    - id: "b9dd3cd3-5b9f-4063-922c-fc808b05374a"
      name: McDonalds
    - id: "d7d96861-19a2-47bc-984d-bdc25c523535"
      name: Pflugervile Taco House
    - id: "1794b53c-6341-497b-b5b3-136abaf490ad"
      name: Burger King
    - id: "871da6f2-12e2-45c2-b963-669a2f1c3275"
      name: Tacos La Catarina
    - id: "73c01364-f3f5-45e0-8a55-f7112b2bf1e2"
      name: Asashi Imports
    - id: "c8bf9ae2-77a1-46d2-bc32-b39240ebeb76"
      name: Kura Sushi
    - id: "b6632906-972e-4ef6-80d4-6fb65390f8b2"
      name: Ramen Tatsuya
    - id: "f7afc807-06e4-4a4a-8413-195f5139fb39"
      name: Stile Switch
    - id: "a148d6d5-3469-4d12-8047-9b6dbe4cd98d"
      name: Bird Bird Biscuit
