server:
  port : 1813
#spring:
  #datasource:
    #url: jdbc:mariadb://localhost:3306/cbBlog
    #username:
    #password:
    #driver-class-name: org.mariadb.jdbc.Driver
  #jpa:
    # Use the below line for Test/Dev Environments.
   # hibernate.ddl-auto: create-drop
    # Use the below line for Prod Environment.
    # hibernate.ddl-auto: none
  logging:
    level:
      root: DEBUG
      org.springframework: DEBUG
      dev.christopherbell.azurras: DEBUG